on:
  pull_request:
    branches:
      "master"
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: cd ./src && make docker-test