on:
  push:
    branches:
      "*"
  pull_request:
    branches:
      "master"
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get inside src folder
        run: cd ./src
      - name: Build Docker Image
        run: make docker-test